# Generated by Django 5.0 on 2023-12-30 19:42

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reversed', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Reverse(models.F('name')), output_field=models.CharField(max_length=100))),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='example', to='example.parent')),
            ],
            options={
                'unique_together': {('name', 'reversed')},
            },
        ),
    ]
